"""added more to the listing table

Revision ID: 64733170f4ea
Revises: 199f6fb5f16b
Create Date: 2020-02-23 08:42:29.576641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64733170f4ea'
down_revision = '199f6fb5f16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('desc', sa.String(), nullable=True))
    op.add_column('listing', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_listing_desc'), 'listing', ['desc'], unique=False)
    op.create_index(op.f('ix_listing_title'), 'listing', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_title'), table_name='listing')
    op.drop_index(op.f('ix_listing_desc'), table_name='listing')
    op.drop_column('listing', 'title')
    op.drop_column('listing', 'desc')
    # ### end Alembic commands ###
