"""posts table

Revision ID: 9ae34407d90c
Revises: 350645f4fb73
Create Date: 2020-02-22 13:38:33.463138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae34407d90c'
down_revision = '350645f4fb73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_body'), 'listing', ['body'], unique=False)
    op.create_index(op.f('ix_listing_timestamp'), 'listing', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_timestamp'), table_name='listing')
    op.drop_index(op.f('ix_listing_body'), table_name='listing')
    op.drop_table('listing')
    # ### end Alembic commands ###
