"""added forms in the lists table

Revision ID: 199f6fb5f16b
Revises: 9ae34407d90c
Create Date: 2020-02-22 21:25:13.674656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199f6fb5f16b'
down_revision = '9ae34407d90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('location', sa.String(), nullable=True))
    op.add_column('listing', sa.Column('type', sa.String(), nullable=True))
    op.create_index(op.f('ix_listing_location'), 'listing', ['location'], unique=False)
    op.create_index(op.f('ix_listing_type'), 'listing', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_type'), table_name='listing')
    op.drop_index(op.f('ix_listing_location'), table_name='listing')
    op.drop_column('listing', 'type')
    op.drop_column('listing', 'location')
    # ### end Alembic commands ###
